<?php 
require_once ROOT_PATH .'\app\models\JsonManager.class.php';

$tasks = JsonManager::readJson();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Ask Name Form</title>
    <!-- <link rel="stylesheet" href="styles.css" /> -->
</head>

<body>
    <div style="max-width: 50%; margin: 0 auto;">
        <h1>Tell me the task name</h1>

        <form action="http://localhost/DevOPS/web/view">
            <label for="taskName">Chose a name:</label>
            <select name="taskName" id="taskName">
                <?php foreach ($tasks as $task):?>
                <option value="<?php echo $task["name"] ?>"><?php echo $task["name"] ?></option>
                <!-- <option value="saab">Saab</option>
                <option value="opel">Opel</option>
                <option value="audi">Audi</option> -->
                <?php endforeach; ?>
            </select>
            <br><br>
            <input type="submit" value="Submit">
        </form>
    </div>
</body>

</html>
<?php 
var_dump($tasks);?>
<html><br><br></html>
<?php 
var_dump($task)
?>