<?php $task = $this->task; $taskId = $this->taskId ?>

<body class="bg-gray-100">
    <div class="bg-gray-100 p-4 max-w-md mx-auto py-6">
        <h1 class="text-3xl font-bold text-center">Edit Task</h1>
        <form class="mt-8 bg-white shadow rounded-lg p-4 mb-4" method="post" action="">
            <div class="mb-4">
                <label for="author" class="block text-gray-700 font-bold mb-2">Your name:</label>
                <input id="author" name="author" type="text" placeholder="Task author" required class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="<?= $task['author'] ?>">
            </div>
            <div class="mb-4">
                <label for="name" class="block text-gray-700 font-bold mb-2">Enter the task title:</label>
                <input id="name" name="name" type="text" placeholder="Walk the dog..." required class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="<?= $task['name'] ?>">
            </div>
            <div class="mb-4">
                <label for="description" class="block text-gray-700 font-bold mb-2">More details?</label>
                <textarea id="description" name="description" rows="1" class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Also talk with neighbors"><?= $task['description'] ?></textarea>
            </div>
            <div class="mb-4">
                <span class="block text-gray-700 font-bold mb-2">Your task is...</span>
                <label class="inline-flex items-center">
                    <input type="radio" name="status" value="Pending" <?= strtolower($task['status'] ?? '') == 'pending' ? 'checked' : '' ?> class="form-radio text-blue-500 focus:ring-blue-500">
                    <span class="ml-2">Pending</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="status" value="Active" <?= strtolower($task['status'] ?? '') == 'active' ? 'checked' : '' ?> class="form-radio text-blue-500 focus:ring-blue-500">
                    <span class="ml-2">Active</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="status" value="Finished" <?= strtolower($task['status'] ?? '') == 'finished' ? 'checked' : '' ?> class="form-radio text-blue-500 focus:ring-blue-500">
                    <span class="ml-2">Finished</span>
                </label>
            </div>
            <div class="flex justify-center">
                <input type="submit" name="updateTask" value="Update" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            </div>
        </form>
    </div>
</body>

</html>