<main class="flex-grow overflow-y-auto">
    <h1 class="text-3xl font-bold text-center p-3">Task List</h1>
    <div class="mb-4">
        <a href="<?= $this->baseUrl() ?>/taskForm" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-4">
            Add a new task
        </a>
    </div>
    <?php if ($this->totalTasks > 0) {

        foreach ($this->tasks as $taskId => $task) {
    ?>
            <div class="bg-white shadow rounded-lg p-3 mb-3 flex flex-col md:flex-row md:items-center justify-between">
                <div class="md:flex-grow">
                    <h3 class="text-lg font-bold mb-2"><?= $task['name'] ?></h3>
                    <p class="text-gray-500 mt-2">
                        Author: <?= $task['author'] ?> | Status: <?= $task['status'] ?>
                    </p>
                </div>
                <div class="md:space-x-2 flex items-center mt-4 md:mt-0">
                    <form method="post" action="<?= $this->baseUrl() ?>/viewTask?taskId=<?= $taskId ?>">
                        <input type="hidden" name="taskId" value="<?= $taskId ?>">
                        <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                            View
                        </button>
                    </form>
                    <a href="<?= $this->baseUrl() ?>/edit?taskId=<?= $taskId ?>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Update
                    </a>
                    <form method="post" action="<?= $this->baseUrl() ?>/deleted">
                        <input type="hidden" name="deleteTaskId" value="<?= $taskId ?>">
                        <button type="submit" onclick="return confirm('Are you sure you want to delete this task?')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        <?php }
        if ($this->totalPages > 1) { ?>
            <div class="mt-3 flex justify-between items-center">
                <?php if ($this->currentPage > 1) { ?>
                    <a href="<?= $this->baseUrl() ?>/showList?page=<?= $this->currentPage - 1 ?>" class="text-blue-500 font-bold ml-4">
                        Previous
                    </a>
                <?php } ?>

                <div class="flex items-center">
                    <div class="text-gray-700 ml-4 mr-4">Go to page:</div>
                    <div class="flex">
                        <?php for ($page = max(1, $this->currentPage - 2); $page <= min($this->currentPage + 2, $this->totalPages); $page++) { ?>
                            <?php if ($page == $this->currentPage) { ?>
                                <div class="px-2 py-1 text-blue-500 font-bold"><?= $page ?></div>
                            <?php } else { ?>
                                <a href="<?= $this->baseUrl() ?>/showList?page=<?= $page ?>" class="px-2 py-1 text-blue-500 font-bold hover:underline"><?= $page ?></a>
                            <?php } ?>
                        <?php } ?>
                        <?php if ($this->currentPage + 2 < $this->totalPages) { ?>
                            <span class="px-2 py-1 text-gray-700">...</span>
                            <a href="<?= $this->baseUrl() ?>/showList?page=<?= $this->totalPages ?>" class="px-2 py-1 text-blue-500 font-bold hover:underline"><?= $totalPages ?></a>
                        <?php } ?>
                    </div>
                </div>

                <?php if ($this->currentPage < $this->totalPages) { ?>
                    <a href="<?= $this->baseUrl() ?>/showList?page=<?= $this->currentPage + 1 ?>" class="text-blue-500 font-bold mr-4">
                        Next
                    </a>
                <?php } ?>
            </div>
    <?php }
    } ?>
</main>