<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>View Task</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<?php
$data = JsonManager::readJson();
if (isset($_POST['deleteTaskId'])) {
    $taskIdToDelete = $_POST['deleteTaskId'];
    if (isset($data[$taskIdToDelete])) {
        // Remove the task from the array
        unset($data[$taskIdToDelete]);
        // Update the JSON file
        JsonManager::writeJson($data);
        // Redirect to the deletedTask page
        header("Location: http://localhost/DevOPS/web/deleted");
        exit;
    }
}
?>

<body class="bg-gray-100">
    <div class="bg-gray-100 p-4">
        <h1 class="text-3xl font-bold text-center">Task List</h1>

        <div class="mb-4">
            <a href="http://localhost/DevOPS/web/taskForm"
                class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Add a new task
            </a>
        </div>

        <?php if (empty($data)): ?>
        <p class="text-gray-700 text-lg">No tasks created yet.</p>
        <?php else: ?>
        <?php foreach ($data as $taskId => $task): ?>
        <div class="bg-white shadow rounded-lg p-4 mb-4 flex flex-col md:flex-row md:items-center justify-between">
            <div class="md:flex-grow">
                <h3 class="text-lg font-bold mb-2"><?= $task['name'] ?></h3>
                <p class="text-gray-500 mt-2">
                    Author: <?= $task['author'] ?> | Status: <?= $task['status'] ?>
                </p>
            </div>
            <div class="md:space-x-2 flex items-center mt-4 md:mt-0">
                <form method="post" action="http://localhost/DevOPS/web/viewTask?taskId=<?= $taskId ?>">
                    <input type="hidden" name="taskId" value="<?= $taskId ?>">
                    <button type="submit"
                        class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                        View
                    </button>
                </form>
                <a href="http://localhost/DevOPS/web/edit?taskId=<?= $taskId ?>"
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Update
                </a>
                <form method="post" action="">
                    <input type="hidden" name="deleteTaskId" value="<?= $taskId ?>">
                    <button type="submit" onclick="return confirm('Are you sure you want to delete this task?')"
                        class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                        Delete
                    </button>
                </form>
            </div>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
</body>

</html>
