<div class="bg-gray-100 p-4">
    <h2 class="text-xl font-bold mb-4">View Task</h2>
    <div class="flex justify-between mb-4">
        <a href="<?= $this->baseUrl() ?>/taskForm" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Add Task
        </a>
        <a href="<?= $this->baseUrl() ?>/showList" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
            Back to Task List
        </a>
    </div>
</div>
<div class="bg-white shadow rounded-lg p-4 mb-4 flex justify-between">
    <div>
        <h3 class="text-lg font-bold mb-2"><?= $this->task['name'] ?></h3>
        <p class="text-gray-700"><?= $this->task['description'] ?></p>
        <p class="text-gray-500 mt-2">
            Author: <?= $this->task['author'] ?> | Status: <?= $this->task['status'] ?>
        </p>
        <p class="text-gray-500">
            Start date: <?= $this->task['startDate'] ?>
        </p>
        <?php if (isset($this->task['endDate'])) : ?>
            <p class="text-gray-500">
                End date: <?= $this->task['endDate'] ?>
            </p>
        <?php endif; ?>
    </div>
    <div class="space-x-2 flex items-center">
        <a href="<?= $this->baseUrl() ?>/edit?taskId=<?= $this->taskId ?>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Update
        </a>
        <form method="post">
            <input type="hidden" name="deleteConfirmed" value="1">
            <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" onclick="return confirm('Are you sure you want to delete this task?');">
                Delete
            </button>
        </form>
    </div>
</div>