<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>ToDo Project</title>
</head>

<body class="bg-gray-100 h-screen flex flex-col">
    <header class="bg-gray-800 text-white font-bold py-2 px-4">
        <nav class="flex justify-between items-center">
            <a href="<?= $this->baseUrl() ?>/ " class="home-link bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Home</a>
        </nav>
    </header>

    <main class="flex-grow">
        <?= $this->content() ?> <!-- Contenido específico de cada página -->
    </main>

    <footer class="bg-gray-800 text-white p-3 text-center mt-auto">
        &copy; <?= date('Y') ?> DevOPS - ToDo Project
    </footer>
</body>

</html>